version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    networks:
      - app-network

  tests:
    image: maven:3.9.7
    volumes:
      - .:/app
    working_dir: /app
    command: ["mvn", "test"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
